# Generated by Django 5.2.9 on 2026-01-03 16:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('event_id', models.UUIDField()),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('actor_id', models.CharField(db_index=True, max_length=100)),
                ('aggregate_type', models.CharField(max_length=100)),
                ('aggregate_id', models.UUIDField(db_index=True)),
                ('event_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['aggregate_type', 'aggregate_id'], name='audit_log_aggrega_984cea_idx'), models.Index(fields=['actor_id', 'occurred_at'], name='audit_log_actor_i_eb9bde_idx')],
            },
        ),
    ]
