# Generated by Django 6.0 on 2026-01-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_add_feature_flag_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='shipping_address',
            field=models.JSONField(default=dict),
        ),
    ]
