# Generated by Django 6.0 on 2026-01-09 14:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_ordermodel_shipping_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroupModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserGroupMembershipModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='django_app.userprofile')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='django_app.usergroupmodel')),
            ],
            options={
                'db_table': 'user_group_membership',
                'constraints': [models.UniqueConstraint(fields=('user_profile', 'group'), name='unique_user_group_membership')],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlagTargetModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_groups', to='django_app.featureflagmodel')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_flags', to='django_app.usergroupmodel')),
            ],
            options={
                'db_table': 'feature_flag_target',
                'constraints': [models.UniqueConstraint(fields=('feature_flag', 'group'), name='unique_flag_target')],
            },
        ),
    ]
